AppCDS/Controllers/InformacionController.cs
using AppCDS.Data;
using AppCDS.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppCDS.Controllers
{
    public class InformacionController : Controller
    {
        private readonly DiscosDBContext _context;

        public InformacionController(DiscosDBContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(DiscoCategoriasViewModel discoCategoriasVM)
        {
            //Obtiene lista de autores
            IQueryable<string> AutoresQuery = _context.Disco.OrderBy(p => p.Autor).Select(p => p.Autor);

            //Obtiene Lista De Años
            IQueryable<int> AniosQuery = _context.Disco.OrderBy(p => p.Anio).Select(p => p.Anio);

            //Obtiene la lista de discos
            var Discos = _context.Disco.Select(x => x);

            //Filtramos en caso que se llene el SearchString
            if (!string.IsNullOrEmpty(discoCategoriasVM.SearchString))
            {
                Discos = Discos.Where(x => x.NombreDisco.Contains(discoCategoriasVM.SearchString));
            }

            //Filtra por Autor
            if (!string.IsNullOrEmpty(discoCategoriasVM.DiscoAutor))
            {
                Discos = Discos.Where(x => x.Autor == discoCategoriasVM.DiscoAutor);
            }

            //Filtra por año
            if (!string.IsNullOrEmpty(discoCategoriasVM.DiscoAnio.ToString()) && discoCategoriasVM.DiscoAnio > 0)
            {
                Discos = Discos.Where(x => x.Anio == discoCategoriasVM.DiscoAnio);
            }

            //Agrego el SelectList de DiscoAutor
            discoCategoriasVM.Autores = new SelectList(await AutoresQuery.Distinct().ToListAsync());

            //Agrego el SelectList de Año
            discoCategoriasVM.Anios = new SelectList(await AniosQuery.Distinct().ToListAsync());

            //Agrego el listado de discos
            discoCategoriasVM.Discos = await Discos.ToListAsync();

            discoCategoriasVM.TotalDiscos = discoCategoriasVM.Discos.Count;

            return View(discoCategoriasVM);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var Disco = await _context.Disco.FirstOrDefaultAsync(x => x.Id == id);

            if(Disco == null)
            {
                return NotFound();
            }

            return View(Disco);
        }

        //GET: InformacionController/Create
        public IActionResult Create()
        {
            return View();
        }

        //POST: InformacionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Autor,NombreDisco,NumeroCanciones,Anio")] Disco disco)
        {
            if (ModelState.IsValid)
            {
                _context.Add(disco);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(disco);
        }

        //GET: InformacionController/Edit/1
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var Disco = await _context.Disco.FindAsync(id);

            if (Disco == null)
            {
                return NotFound();
            }

            return View(Disco);
        }

        //POST: InformacionController/Edit/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Autor,NombreDisco,NumeroCanciones,Anio")] Disco disco)
        {
            if(id != disco.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(disco);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DiscoExists(disco.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return RedirectToAction(nameof(Details), disco);
        }

        // GET: InformacionController/Delete/1
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var Disco = await _context.Disco.FirstOrDefaultAsync(m => m.Id == id);

            if (Disco == null)
            {
                return NotFound();
            }

            return View(Disco);
        }

        // POST: InformacionController/Delete/1
        [HttpPost]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Disco = await _context.Disco.FindAsync(id);
            _context.Disco.Remove(Disco);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool DiscoExists(int id)
        {
            return _context.Disco.Any(x => x.Id == id);
        }
    }
}

AppCDS/Views/Informacion/Create.cshtml
@model AppCDS.Models.Disco

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Disco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreDisco" class="control-label"></label>
                <input asp-for="NombreDisco" class="form-control" />
                <span asp-validation-for="NombreDisco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCanciones" class="control-label"></label>
                <input asp-for="NumeroCanciones" class="form-control" />
                <span asp-validation-for="NumeroCanciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppCDS/Views/Informacion/Delete.cshtml
@model AppCDS.Models.Disco

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Disco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreDisco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreDisco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCanciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroCanciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
    
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppCDS/Views/Informacion/Details.cshtml
@model AppCDS.Models.Disco

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Disco</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreDisco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreDisco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroCanciones)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroCanciones)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AppCDS/Views/Informacion/Edit.cshtml
@model AppCDS.Models.Disco

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Disco</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NombreDisco" class="control-label"></label>
                <input asp-for="NombreDisco" class="form-control" />
                <span asp-validation-for="NombreDisco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroCanciones" class="control-label"></label>
                <input asp-for="NumeroCanciones" class="form-control" />
                <span asp-validation-for="NumeroCanciones" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppCDS/Views/Informacion/Index.cshtml
@model AppCDS.Models.DiscoCategoriasViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Discos. Existen un total de @Model.TotalDiscos</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Informacion" asp-action="Index" method="get">
    <p>
        <select asp-for="DiscoAutor" asp-items="Model.Autores">
            <option value="">All Discos</option>
        </select>

        <select asp-for="DiscoAnio" asp-items="Model.Anios">
            <option value="">All Años</option>
        </select>

        Disco: <input type="text" name="SearchString" />
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Discos[0].Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discos[0].NombreDisco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discos[0].NumeroCanciones)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discos[0].Anio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Discos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreDisco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroCanciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anio)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>